function varargout=sym_fhn(action,varargin)
%% Automatically generated with matlabFunction
% 
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'ntau'
   varargout{1}=2;
   return
  case 'tp_del'
   varargout{1}=0;
   return
  case 'maxorder'
   varargout{1}=5;
   return
  case 'directional_derivative'
   varargout{1}=0;
   return
end
ind=varargin{1};
order=varargin{2};
nout=varargin{3};
f=str2func(sprintf('sym_fhn_%s_%d_%d',action,ind,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{4:end});




function [out1,out2] = sym_fhn_rhs_1_0(x1_1,x2_1,x1_2,x2_2,x1_3,x2_3,I,c,tau1,tau2,l1,l2,phi,T,k)
%SYM_FHN_RHS_1_0
%    [OUT1,OUT2] = SYM_FHN_RHS_1_0(X1_1,X2_1,X1_2,X2_2,X1_3,X2_3,I,C,TAU1,TAU2,L1,L2,PHI,T,K)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    28-Aug-2024 18:50:09

out1 = I+x1_1-x2_1-x1_1.^3./3.0+c.*(x1_1.*-2.0+x1_2+x1_3);
if nargout > 1
    out2 = x1_1.*(2.0./2.5e+1)-x2_1.*(8.0./1.25e+2)+7.0./1.25e+2;
end


function [out1,out2] = sym_fhn_rhs_1_1(x1_1,x2_1,x1_2,x2_2,x1_3,x2_3,I,c,tau1,tau2,l1,l2,phi,T,k,x1_1_d,x2_1_d,x1_2_d,x2_2_d,x1_3_d,x2_3_d,I_d,c_d,tau1_d,tau2_d,l1_d,l2_d,phi_d,T_d,k_d)
%SYM_FHN_RHS_1_1
%    [OUT1,OUT2] = SYM_FHN_RHS_1_1(X1_1,X2_1,X1_2,X2_2,X1_3,X2_3,I,C,TAU1,TAU2,L1,L2,PHI,T,K,X1_1_D,X2_1_D,X1_2_D,X2_2_D,X1_3_D,X2_3_D,I_d,C_D,TAU1_D,TAU2_D,L1_D,L2_D,PHI_D,T_d,K_D)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    28-Aug-2024 18:50:09

out1 = I_d+x1_1_d-x2_1_d-x1_1.^2.*x1_1_d+c.*(x1_1_d.*-2.0+x1_2_d+x1_3_d)+c_d.*(x1_1.*-2.0+x1_2+x1_3);
if nargout > 1
    out2 = x1_1_d.*(2.0./2.5e+1)-x2_1_d.*(8.0./1.25e+2);
end


function [out1,out2] = sym_fhn_rhs_1_2(x1_1,x2_1,x1_2,x2_2,x1_3,x2_3,I,c,tau1,tau2,l1,l2,phi,T,k,x1_1_d,x2_1_d,x1_2_d,x2_2_d,x1_3_d,x2_3_d,x1_1_d_d,x2_1_d_d,x1_2_d_d,x2_2_d_d,x1_3_d_d,x2_3_d_d,I_d,c_d,tau1_d,tau2_d,l1_d,l2_d,phi_d,T_d,k_d,I_d_d,c_d_d,tau1_d_d,tau2_d_d,l1_d_d,l2_d_d,phi_d_d,T_d_d,k_d_d)
%SYM_FHN_RHS_1_2
%    [OUT1,OUT2] = SYM_FHN_RHS_1_2(X1_1,X2_1,X1_2,X2_2,X1_3,X2_3,I,C,TAU1,TAU2,L1,L2,PHI,T,K,X1_1_D,X2_1_D,X1_2_D,X2_2_D,X1_3_D,X2_3_D,X1_1_D_D,X2_1_D_D,X1_2_D_D,X2_2_D_D,X1_3_D_D,X2_3_D_D,I_d,C_D,TAU1_D,TAU2_D,L1_D,L2_D,PHI_D,T_d,K_D,I_d_d,C_D_D,TAU1_D_D,TAU2_D_D,L1_D_D,L2_D_D,PHI_D_D,T_d_d,K_D_D)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    28-Aug-2024 18:50:09

t2 = x1_1_d.*-2.0;
t3 = x1_1_d_d.*-2.0;
out1 = c_d_d.*(t2+x1_2_d+x1_3_d)+c_d.*(t3+x1_2_d_d+x1_3_d_d)+t2.*x1_1.*x1_1_d_d;
if nargout > 1
    out2 = 0.0;
end


function [out1,out2] = sym_fhn_rhs_1_3(x1_1,x2_1,x1_2,x2_2,x1_3,x2_3,I,c,tau1,tau2,l1,l2,phi,T,k,x1_1_d,x2_1_d,x1_2_d,x2_2_d,x1_3_d,x2_3_d,x1_1_d_d,x2_1_d_d,x1_2_d_d,x2_2_d_d,x1_3_d_d,x2_3_d_d,x1_1_d_d_d,x2_1_d_d_d,x1_2_d_d_d,x2_2_d_d_d,x1_3_d_d_d,x2_3_d_d_d,I_d,c_d,tau1_d,tau2_d,l1_d,l2_d,phi_d,T_d,k_d,I_d_d,c_d_d,tau1_d_d,tau2_d_d,l1_d_d,l2_d_d,phi_d_d,T_d_d,k_d_d,I_d_d_d,c_d_d_d,tau1_d_d_d,tau2_d_d_d,l1_d_d_d,l2_d_d_d,phi_d_d_d,T_d_d_d,k_d_d_d)
%SYM_FHN_RHS_1_3
%    [OUT1,OUT2] = SYM_FHN_RHS_1_3(X1_1,X2_1,X1_2,X2_2,X1_3,X2_3,I,C,TAU1,TAU2,L1,L2,PHI,T,K,X1_1_D,X2_1_D,X1_2_D,X2_2_D,X1_3_D,X2_3_D,X1_1_D_D,X2_1_D_D,X1_2_D_D,X2_2_D_D,X1_3_D_D,X2_3_D_D,X1_1_D_D_D,X2_1_D_D_D,X1_2_D_D_D,X2_2_D_D_D,X1_3_D_D_D,X2_3_D_D_D,I_d,C_D,TAU1_D,TAU2_D,L1_D,L2_D,PHI_D,T_d,K_D,I_d_d,C_D_D,TAU1_D_D,TAU2_D_D,L1_D_D,L2_D_D,PHI_D_D,T_d_d,K_D_D,I_d_d_d,C_D_D_D,TAU1_D_D_D,TAU2_D_D_D,L1_D_D_D,L2_D_D_D,PHI_D_D_D,T_d_d_d,K_D_D_D)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    28-Aug-2024 18:50:09

out1 = x1_1_d.*x1_1_d_d.*x1_1_d_d_d.*-2.0;
if nargout > 1
    out2 = 0.0;
end


function [out1,out2] = sym_fhn_rhs_1_4(x1_1,x2_1,x1_2,x2_2,x1_3,x2_3,I,c,tau1,tau2,l1,l2,phi,T,k,x1_1_d,x2_1_d,x1_2_d,x2_2_d,x1_3_d,x2_3_d,x1_1_d_d,x2_1_d_d,x1_2_d_d,x2_2_d_d,x1_3_d_d,x2_3_d_d,x1_1_d_d_d,x2_1_d_d_d,x1_2_d_d_d,x2_2_d_d_d,x1_3_d_d_d,x2_3_d_d_d,x1_1_d_d_d_d,x2_1_d_d_d_d,x1_2_d_d_d_d,x2_2_d_d_d_d,x1_3_d_d_d_d,x2_3_d_d_d_d,I_d,c_d,tau1_d,tau2_d,l1_d,l2_d,phi_d,T_d,k_d,I_d_d,c_d_d,tau1_d_d,tau2_d_d,l1_d_d,l2_d_d,phi_d_d,T_d_d,k_d_d,I_d_d_d,c_d_d_d,tau1_d_d_d,tau2_d_d_d,l1_d_d_d,l2_d_d_d,phi_d_d_d,T_d_d_d,k_d_d_d,I_d_d_d_d,c_d_d_d_d,tau1_d_d_d_d,tau2_d_d_d_d,l1_d_d_d_d,l2_d_d_d_d,phi_d_d_d_d,T_d_d_d_d,k_d_d_d_d)
%SYM_FHN_RHS_1_4
%    [OUT1,OUT2] = SYM_FHN_RHS_1_4(X1_1,X2_1,X1_2,X2_2,X1_3,X2_3,I,C,TAU1,TAU2,L1,L2,PHI,T,K,X1_1_D,X2_1_D,X1_2_D,X2_2_D,X1_3_D,X2_3_D,X1_1_D_D,X2_1_D_D,X1_2_D_D,X2_2_D_D,X1_3_D_D,X2_3_D_D,X1_1_D_D_D,X2_1_D_D_D,X1_2_D_D_D,X2_2_D_D_D,X1_3_D_D_D,X2_3_D_D_D,X1_1_D_D_D_D,X2_1_D_D_D_D,X1_2_D_D_D_D,X2_2_D_D_D_D,X1_3_D_D_D_D,X2_3_D_D_D_D,I_d,C_D,TAU1_D,TAU2_D,L1_D,L2_D,PHI_D,T_d,K_D,I_d_d,C_D_D,TAU1_D_D,TAU2_D_D,L1_D_D,L2_D_D,PHI_D_D,T_d_d,K_D_D,I_d_d_d,C_D_D_D,TAU1_D_D_D,TAU2_D_D_D,L1_D_D_D,L2_D_D_D,PHI_D_D_D,T_d_d_d,K_D_D_D,I_d_d_d_d,C_D_D_D_D,TAU1_D_D_D_D,TAU2_D_D_D_D,L1_D_D_D_D,L2_D_D_D_D,PHI_D_D_D_D,T_d_d_d_d,K_D_D_D_D)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    28-Aug-2024 18:50:10

out1 = 0.0;
if nargout > 1
    out2 = 0.0;
end


function [out1,out2] = sym_fhn_rhs_1_5(x1_1,x2_1,x1_2,x2_2,x1_3,x2_3,I,c,tau1,tau2,l1,l2,phi,T,k,x1_1_d,x2_1_d,x1_2_d,x2_2_d,x1_3_d,x2_3_d,x1_1_d_d,x2_1_d_d,x1_2_d_d,x2_2_d_d,x1_3_d_d,x2_3_d_d,x1_1_d_d_d,x2_1_d_d_d,x1_2_d_d_d,x2_2_d_d_d,x1_3_d_d_d,x2_3_d_d_d,x1_1_d_d_d_d,x2_1_d_d_d_d,x1_2_d_d_d_d,x2_2_d_d_d_d,x1_3_d_d_d_d,x2_3_d_d_d_d,x1_1_d_d_d_d_d,x2_1_d_d_d_d_d,x1_2_d_d_d_d_d,x2_2_d_d_d_d_d,x1_3_d_d_d_d_d,x2_3_d_d_d_d_d,I_d,c_d,tau1_d,tau2_d,l1_d,l2_d,phi_d,T_d,k_d,I_d_d,c_d_d,tau1_d_d,tau2_d_d,l1_d_d,l2_d_d,phi_d_d,T_d_d,k_d_d,I_d_d_d,c_d_d_d,tau1_d_d_d,tau2_d_d_d,l1_d_d_d,l2_d_d_d,phi_d_d_d,T_d_d_d,k_d_d_d,I_d_d_d_d,c_d_d_d_d,tau1_d_d_d_d,tau2_d_d_d_d,l1_d_d_d_d,l2_d_d_d_d,phi_d_d_d_d,T_d_d_d_d,k_d_d_d_d,I_d_d_d_d_d,c_d_d_d_d_d,tau1_d_d_d_d_d,tau2_d_d_d_d_d,l1_d_d_d_d_d,l2_d_d_d_d_d,phi_d_d_d_d_d,T_d_d_d_d_d,k_d_d_d_d_d)
%SYM_FHN_RHS_1_5
%    [OUT1,OUT2] = SYM_FHN_RHS_1_5(X1_1,X2_1,X1_2,X2_2,X1_3,X2_3,I,C,TAU1,TAU2,L1,L2,PHI,T,K,X1_1_D,X2_1_D,X1_2_D,X2_2_D,X1_3_D,X2_3_D,X1_1_D_D,X2_1_D_D,X1_2_D_D,X2_2_D_D,X1_3_D_D,X2_3_D_D,X1_1_D_D_D,X2_1_D_D_D,X1_2_D_D_D,X2_2_D_D_D,X1_3_D_D_D,X2_3_D_D_D,X1_1_D_D_D_D,X2_1_D_D_D_D,X1_2_D_D_D_D,X2_2_D_D_D_D,X1_3_D_D_D_D,X2_3_D_D_D_D,X1_1_D_D_D_D_D,X2_1_D_D_D_D_D,X1_2_D_D_D_D_D,X2_2_D_D_D_D_D,X1_3_D_D_D_D_D,X2_3_D_D_D_D_D,I_d,C_D,TAU1_D,TAU2_D,L1_D,L2_D,PHI_D,T_d,K_D,I_d_d,C_D_D,TAU1_D_D,TAU2_D_D,L1_D_D,L2_D_D,PHI_D_D,T_d_d,K_D_D,I_d_d_d,C_D_D_D,TAU1_D_D_D,TAU2_D_D_D,L1_D_D_D,L2_D_D_D,PHI_D_D_D,T_d_d_d,K_D_D_D,I_d_d_d_d,C_D_D_D_D,TAU1_D_D_D_D,TAU2_D_D_D_D,L1_D_D_D_D,L2_D_D_D_D,PHI_D_D_D_D,T_d_d_d_d,K_D_D_D_D,I_d_d_d_d_d,C_D_D_D_D_D,TAU1_D_D_D_D_D,TAU2_D_D_D_D_D,L1_D_D_D_D_D,L2_D_D_D_D_D,PHI_D_D_D_D_D,T_d_d_d_d_d,K_D_D_D_D_D)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    28-Aug-2024 18:50:10

out1 = 0.0;
if nargout > 1
    out2 = 0.0;
end

